openapi: 3.0.0

info:
  version: 0.1.0
  title: IEEE SB Application
  description: >-
    A great way to manage your branch and advertise your content
  baseUrl: /v1

security:
  - application:
      - read
      - write

paths:
  # Utilities
  /ping:
    $include: "./routes/utils/ping.yaml"

  # Users
  /users:
    $include: "./routes/v1/users/users.yaml"
  /user/{user_id}:
    $include: "./routes/v1/users/users_id.yaml"

  # Authorization
  /login:
    $include: "./routes/v1/auth/login.yaml"
  /logout:
    $include: "./routes/v1/auth/logout.yaml"
  /profile:
    $include: "./routes/v1/auth/profile.yaml"

  # Events
  /events:
    $include: "./routes/v1/events/events.yaml"
  /events/{event_id}:
    $include: "./routes/v1/events/events_id.yaml"

  # Sponsors
  /sponsors:
    $include: "./routes/v1/sponsors/sponsors.yaml"
  /sponsors/{sponsor_id}:
    $include: "./routes/v1/sponsors/sponsors_id.yaml"

  # Tickets
  /tickets:
    $include: "./routes/v1/tickets/tickets.yaml"
  /ticket/{sponsor_id}:
    $include: "./routes/v1/tickets/tickets_id.yaml"
  /tickets/contact:
    $include: "./routes/v1/tickets/tickets_contact.yaml"

  # Media
  /media/upload:
    $include: "./routes/v1/media/media_upload.yaml"
  /media/download/{media_id}:
    $include: "./routes/v1/media/media_download_id.yaml"

components:
  schemas:
    User:
      $include: "./components/schemas/User.yaml"
    UserObject:
      $include: "./components/schemas/User.object.yaml"
